### ISSUE TITLE
Sinon error

### ISSUE THREAD

**Issue by grandballoon** [learn-co-curriculum/react-component-mounting-lab#1]
Hi,

My code works perfectly and is identical to the solution code, but I get the following error:

  1) <App />
       calls componentDidMount and adds a quote:
     TypeError: Attempted to wrap undefined property componentDidMount as function
      at wrapMethod (node_modules/sinon/lib/sinon/util/core/wrap-method.js:70:21)
      at Function.spy (node_modules/sinon/lib/sinon/spy.js:45:16)
      at spy (node_modules/sinon/lib/sinon/sandbox.js:274:26)
      at Context.<anonymous> (test/index.test.js:17:5)

I haven't touched the sinon file or anything like that. Here is my code for comparison:

```
import React, { Component } from 'react';

import Timer from './Timer'

class App extends Component {

  //no props being used here, so we can use the shorthand declaration of state
  state = {
    timerIDs: []
  }

componentDidMount = () => {
  this.handleAddTimer()
}

  //Your code here:









  // No need to modify anything in render or the class methods below
  // Unless, of course, you're curious about how it all works
  render() {

    return (
      <div className="App">
        <h1>MultiTimer</h1>
        <button onClick={this.handleAddTimer}>Add New Timer</button>

        <div className="TimerGrid">
          {this.renderTimers()}
        </div>

      </div>
    );
  }

  // returns array of components written in JSX, mapped from this.state.timerIDs
  renderTimers = () => this.state.timerIDs.map(id => {
    return <Timer key={id} id={id} removeTimer={this.removeTimer} />
  })

  // adds a random number for timer ID
  handleAddTimer = () => {
    this.setState(prevState => ({
      timerIDs: [...prevState.timerIDs, Math.floor(Math.random()*1000)]
    }))
  }

  // removeTimer updates state, removing any timer that matches the provided author
  removeTimer = id => {
    this.setState(prevState => ({
      timerIDs: prevState.timerIDs.filter(timer_id => timer_id !== id)
    }))
  }


}

export default App;

```

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @grandballoon.

We have updated the readme to include an additional note regarding this issue. The issue stems from the use of arrow functions and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
